---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ monasca_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}/{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: monasca_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ monasca_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over monasca-agent-collector config
  vars:
    service: "{{ monasca_services['monasca-agent-collector'] }}"
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/monasca-agent-collector/{{ item }}.j2"
      - "{{ node_custom_config }}/monasca/{{ item }}"
      - "{{ node_custom_config }}/monasca/{{ inventory_hostname }}/{{ item }}"
    dest: "{{ node_config_directory }}/monasca-agent-collector/{{ item }}"
    mode: "0660"
  become: true
  register: monasca_agent_collector_confs
  with_items:
    - agent-collector.yml
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart monasca-agent-collector container

- name: Ensuring monasca-agent collector plugin config directory exists
  vars:
    service: "{{ monasca_services['monasca-agent-collector'] }}"
  file:
    path: "{{ node_config_directory }}/monasca-agent-collector/plugins"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool

- name: Find monasca-agent-collector plugin configuration files
  local_action:
    module: find
    paths:
      - "{{ role_path }}/templates/monasca-agent-collector/plugins/"
      - "{{ node_custom_config }}/monasca/agent_plugins/"
      - "{{ node_custom_config }}/monasca/{{ inventory_hostname }}/agent_plugins/"
    patterns: '*.yaml'
  run_once: True
  register: agent_plugins

- name: Copying over monasca-agent-collector system plugins
  vars:
    service: "{{ monasca_services['monasca-agent-collector'] }}"
  template:
    src: "{{ item.path }}"
    dest: "{{ node_config_directory }}/monasca-agent-collector/plugins/{{ item.path | basename }}"
    mode: "0660"
  become: true
  register: monasca_agent_collector_plugin_confs
  with_items:
    - "{{ agent_plugins.files }}"
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart monasca-agent-collector container

- name: Copying over monasca-agent-collector service plugin
  vars:
    service: "{{ monasca_services['monasca-agent-collector'] }}"
    plugin_regex: "monasca-agent-collector-plugin-(?P<plugin>[\\w]+)"
    plugin_groups: "{{ group_names | map('regex_search', plugin_regex) | select | list }}"
    plugins: "{{ plugin_groups | map('regex_replace', plugin_regex, '\\g<plugin>') | list }}"
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/monasca-agent-collector/service_plugins/{{ item }}.yaml.j2"
      - "{{ node_custom_config }}/monasca/service_plugins/{{ item }}.yaml"
      - "{{ node_custom_config }}/monasca/{{ inventory_hostname }}/service_plugins/{{ item }}.yaml"
    dest: "{{ node_config_directory }}/monasca-agent-collector/plugins/{{ item }}.yaml"
    mode: "0660"
  become: true
  with_items:
    - "{{ plugins }}"
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart monasca-agent-collector container

- name: Copying over monasca-agent-forwarder config
  vars:
    service: "{{ monasca_services['monasca-agent-forwarder'] }}"
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/monasca-agent-forwarder/{{ item }}.j2"
      - "{{ node_custom_config }}/monasca/{{ item }}"
      - "{{ node_custom_config }}/monasca/{{ inventory_hostname }}/{{ item }}"
    dest: "{{ node_config_directory }}/monasca-agent-forwarder/{{ item }}"
    mode: "0660"
  become: true
  register: monasca_agent_forwarder_confs
  with_items:
    - agent-forwarder.yml
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart monasca-agent-forwarder container

- name: Copying over monasca-agent-statsd config
  vars:
    service: "{{ monasca_services['monasca-agent-statsd'] }}"
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/monasca-agent-statsd/{{ item }}.j2"
      - "{{ node_custom_config }}/monasca/{{ item }}"
      - "{{ node_custom_config }}/monasca/{{ inventory_hostname }}/{{ item }}"
    dest: "{{ node_config_directory }}/monasca-agent-statsd/{{ item }}"
    mode: "0660"
  become: true
  register: monasca_agent_statsd_confs
  with_items:
    - agent-statsd.yml
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart monasca-agent-statsd container

- name: Check monasca containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    pid_mode: "{{ item.value.pid_mode|default('') }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
  register: check_monasca_containers
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ monasca_services }}"
  notify:
    - "Restart {{ item.key }} container"
